### ISSUE TITLE
can not import iou3d_cuda

### ISSUE THREAD

**Issue by ShellMount** [happinesslz/EPNet#10]
I got a issue when run  `run_eval_model.sh`  

===================================
ENV INFO:
Ubuntu 18.04
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) 
Python: 3.6.9
torch: 1.2.0
CUDA Version 10.0.130

===================================
error message like below:
```
$ bash run_eval_model.sh 
Traceback (most recent call last):
  File "eval_rcnn.py", line 7, in <module>
    from lib.net.point_rcnn import PointRCNN
  File "/home/ubuntu/ShareFiles/xieyi/epnet/EPNet-master/tools/../lib/net/point_rcnn.py", line 3, in <module>
    from lib.net.rpn import RPN
  File "/home/ubuntu/ShareFiles/xieyi/epnet/EPNet-master/tools/../lib/net/rpn.py", line 4, in <module>
    from lib.rpn.proposal_layer import ProposalLayer
  File "/home/ubuntu/ShareFiles/xieyi/epnet/EPNet-master/tools/../lib/rpn/proposal_layer.py", line 6, in <module>
    import lib.utils.iou3d.iou3d_utils as iou3d_utils
  File "/home/ubuntu/ShareFiles/xieyi/epnet/EPNet-master/tools/../lib/utils/iou3d/iou3d_utils.py", line 2, in <module>
    import iou3d_cuda
ImportError: /home/ubuntu/ShareFiles/xieyi/epnet/EPNet-master/py36/lib/python3.6/site-packages/iou3d-0.0.0-py3.6-linux-x86_64.egg/iou3d_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at19NonVariableTypeMode10is_enabledEv

```

**Comment by happinesslz** [comment]
@ShellMount  
Before running the code, please build and install the pointnet2_lib, iou3d, roipool3d libraries by executing the following command:
`bash build_and_install.sh`

**Comment by ShellMount** [comment]
I have built and installed pointnet2_lib, iou3d, roipool3d by
```
bash build_and_install.sh
```

and the result like the issue above.
@happinesslz

**Comment by pummi823** [comment]
The same question!!!!!!!!!!have you solved it??????
