### ISSUE TITLE
sh build_and_install.sh

### ISSUE THREAD

**Issue by xiaomonv111** [happinesslz/EPNet#45]
when I use "sh build_and_install.sh"  but home/dxy/deepl/EPNet/pointnet2_lib/pointnet2/build/temp.linux-x86_64-cpython-37/src/group_points.o 
c++ -MMD -MF /home/dxy/deepl/EPNet/pointnet2_lib/pointnet2/build/temp.linux-x86_64-cpython-37/src/group_points.o.d -pthread -B /home/dxy/miniconda3/envs/openmmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/torch/include -I/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/torch/include/TH -I/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/dxy/miniconda3/envs/openmmlab/include/python3.7m -c -c /home/dxy/deepl/EPNet/pointnet2_lib/pointnet2/src/group_points.cpp -o /home/dxy/deepl/EPNet/pointnet2_lib/pointnet2/build/temp.linux-x86_64-cpython-37/src/group_points.o -g -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=pointnet2_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command-line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/home/dxy/deepl/EPNet/pointnet2_lib/pointnet2/src/group_points.cpp:5:10: fatal error: THC/THC.h: 没有那个文件或目录
    5 | #include <THC/THC.h>
      |          ^~~~~~~~~~~
compilation terminated.
[2/4] c++ -MMD -MF /home/dxy/deepl/EPNet/pointnet2_lib/pointnet2/build/temp.linux-x86_64-cpython-37/src/interpolate.o.d -pthread -B /home/dxy/miniconda3/envs/openmmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/torch/include -I/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/torch/include/TH -I/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/dxy/miniconda3/envs/openmmlab/include/python3.7m -c -c /home/dxy/deepl/EPNet/pointnet2_lib/pointnet2/src/interpolate.cpp -o /home/dxy/deepl/EPNet/pointnet2_lib/pointnet2/build/temp.linux-x86_64-cpython-37/src/interpolate.o -g -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=pointnet2_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: /home/dxy/deepl/EPNet/pointnet2_lib/pointnet2/build/temp.linux-x86_64-cpython-37/src/interpolate.o 
c++ -MMD -MF /home/dxy/deepl/EPNet/pointnet2_lib/pointnet2/build/temp.linux-x86_64-cpython-37/src/interpolate.o.d -pthread -B /home/dxy/miniconda3/envs/openmmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/torch/include -I/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/torch/include/TH -I/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/dxy/miniconda3/envs/openmmlab/include/python3.7m -c -c /home/dxy/deepl/EPNet/pointnet2_lib/pointnet2/src/interpolate.cpp -o /home/dxy/deepl/EPNet/pointnet2_lib/pointnet2/build/temp.linux-x86_64-cpython-37/src/interpolate.o -g -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=pointnet2_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command-line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/home/dxy/deepl/EPNet/pointnet2_lib/pointnet2/src/interpolate.cpp:3:10: fatal error: THC/THC.h: 没有那个文件或目录
    3 | #include <THC/THC.h>
      |          ^~~~~~~~~~~
compilation terminated.
[3/4] c++ -MMD -MF /home/dxy/deepl/EPNet/pointnet2_lib/pointnet2/build/temp.linux-x86_64-cpython-37/src/ball_query.o.d -pthread -B /home/dxy/miniconda3/envs/openmmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/torch/include -I/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/torch/include/TH -I/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/dxy/miniconda3/envs/openmmlab/include/python3.7m -c -c /home/dxy/deepl/EPNet/pointnet2_lib/pointnet2/src/ball_query.cpp -o /home/dxy/deepl/EPNet/pointnet2_lib/pointnet2/build/temp.linux-x86_64-cpython-37/src/ball_query.o -g -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=pointnet2_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: /home/dxy/deepl/EPNet/pointnet2_lib/pointnet2/build/temp.linux-x86_64-cpython-37/src/ball_query.o 
c++ -MMD -MF /home/dxy/deepl/EPNet/pointnet2_lib/pointnet2/build/temp.linux-x86_64-cpython-37/src/ball_query.o.d -pthread -B /home/dxy/miniconda3/envs/openmmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/torch/include -I/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/torch/include/TH -I/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/dxy/miniconda3/envs/openmmlab/include/python3.7m -c -c /home/dxy/deepl/EPNet/pointnet2_lib/pointnet2/src/ball_query.cpp -o /home/dxy/deepl/EPNet/pointnet2_lib/pointnet2/build/temp.linux-x86_64-cpython-37/src/ball_query.o -g -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=pointnet2_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command-line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/home/dxy/deepl/EPNet/pointnet2_lib/pointnet2/src/ball_query.cpp:3:10: fatal error: THC/THC.h: 没有那个文件或目录
    3 | #include <THC/THC.h>
      |          ^~~~~~~~~~~
compilation terminated.
[4/4] c++ -MMD -MF /home/dxy/deepl/EPNet/pointnet2_lib/pointnet2/build/temp.linux-x86_64-cpython-37/src/sampling.o.d -pthread -B /home/dxy/miniconda3/envs/openmmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/torch/include -I/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/torch/include/TH -I/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/dxy/miniconda3/envs/openmmlab/include/python3.7m -c -c /home/dxy/deepl/EPNet/pointnet2_lib/pointnet2/src/sampling.cpp -o /home/dxy/deepl/EPNet/pointnet2_lib/pointnet2/build/temp.linux-x86_64-cpython-37/src/sampling.o -g -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=pointnet2_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: /home/dxy/deepl/EPNet/pointnet2_lib/pointnet2/build/temp.linux-x86_64-cpython-37/src/sampling.o 
c++ -MMD -MF /home/dxy/deepl/EPNet/pointnet2_lib/pointnet2/build/temp.linux-x86_64-cpython-37/src/sampling.o.d -pthread -B /home/dxy/miniconda3/envs/openmmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/torch/include -I/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/torch/include/TH -I/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/dxy/miniconda3/envs/openmmlab/include/python3.7m -c -c /home/dxy/deepl/EPNet/pointnet2_lib/pointnet2/src/sampling.cpp -o /home/dxy/deepl/EPNet/pointnet2_lib/pointnet2/build/temp.linux-x86_64-cpython-37/src/sampling.o -g -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=pointnet2_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command-line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/home/dxy/deepl/EPNet/pointnet2_lib/pointnet2/src/sampling.cpp:4:10: fatal error: THC/THC.h: 没有那个文件或目录
    4 | #include <THC/THC.h>
      |          ^~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1906, in _run_ninja_build
    env=env)
  File "/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 22, in <module>
    cmdclass = { 'build_ext': BuildExtension }
  File "/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/setuptools/command/install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/setuptools/_distutils/command/install_lib.py", line 112, in build
    self.run_command('build_ext')
  File "/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
    self.build_extensions()
  File "/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
    build_ext.build_extensions(self)
  File "/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 468, in build_extensions
    self._build_extensions_serial()
  File "/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 494, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/Cython/Distutils/build_ext.py", line 127, in build_extension
    super(build_ext, self).build_extension(ext)
  File "/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 556, in build_extension
    depends=ext.depends,
  File "/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 668, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1578, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/dxy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1916, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

**Comment by DeathFish798** [comment]
I solve it by installing old version of pytorch

**Comment by tianl18** [comment]
ref: https://github.com/sshaoshuai/Pointnet2.PyTorch/pull/42/files
and https://github.com/sshaoshuai/PointRCNN/pull/184/files

it works for me. CUDA 11.1 PyTorch 1.8.1+cu111 in A800
